# Generated by Django 4.1 on 2022-09-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.class')),
            ],
        ),
        migrations.AddField(
            model_name='attendence',
            name='classAttendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.classattendence'),
        ),
    ]
